### ISSUE TITLE
双向通信时客户端炸了

### ISSUE THREAD

**Issue by vipcxj** [zishang520/engine.io#10]
服务端是go写的，所以用的这个库，客户端c++，用的[socket.io-client-cpp](https://github.com/socketio/socket.io-client-cpp)，之前都没出问题，直到最近我希望服务端能在建立连接后自动向客户端发送房间内所有用户信息。结果就杯具了。
具体流程如下，服务端获取到新的socket后，向集群广播请求同房间内所有用户信息，然后收到一个就往客户端发，因为这个过程很快，所以估计客户端发的connect消息和服务端主动发送的用户信息撞上了，表现为客户端不是卡住，（一直等待ack，很久之后出现后面的错误），就是获得不正常的包。经过调试后发现这个包的payload是“4”，这里4应该代表是TxtMessage，但后面本来应该跟个代表消息类型的数字，结果只有一个4，客户端取payload[1]时就杯具了。除此之外偶尔能正常连接，反正就是随机的，50%以上概率只返回一个4。请问到底哪里出问题了？难道socket.io不支持全双工？客户端和服务端不能同时发送消息吗？
我去掉服务端主动发消息的代码就一切正常~
最初我以为是因为服务端发送消息是客户端完全建立连接之前，所以我做了下改动，客户端调用connect后，先发送一个evt为setup的消息，服务端收到setup消息后再开始往客户端发消息。但并没有什么卵用~

**Comment by zishang520** [comment]
This issue has been fixed, please use socket.io v2.1.0
