### ISSUE TITLE
Client code 4

### ISSUE THREAD

**Issue by mmavka** [zishang520/engine.io#11]
Good afternoon. Sorry for the noob question. On the client, I receive a message with code 4. I found it to be a connection error (maybe I was wrong). If so, can I configure the server so that it doesn't send code 4? 
![Screenshot 2024-05-06 142632](https://github.com/zishang520/socket.io/assets/6159873/7a31030e-98b1-4b8b-8d63-6f171d8cb308)

**Comment by zishang520** [comment]
This issue has been fixed, please use socket.io v2.1.0.
